name: ExplosiveCrossbow
version: ${project.version}
description: This plugin adds an explosive crossbow to the game
author: tbm00
main: dev.tbm00.spigot.explosivecrossbow.ExplosiveCrossbow
api-version: 1.17